<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InterestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * the modell can be found in app/Models/Interest.php
     */
    
    public function run(): void
    {
        DB::table('interests')->insert([
            ['name' => 'Cooking'],
            ['name' => 'Hiking'],
            ['name' => 'Football'],
            ['name' => 'Programming'],
            ['name' => 'Reading'],
            ['name' => 'Gardening'],
            ['name' => 'Photography'],
            ['name' => 'Traveling'],
            ['name' => 'Painting'],
            ['name' => 'Cycling'],
            ['name' => 'Fishing'],
            ['name' => 'Swimming'],
            ['name' => 'Dancing'],
            ['name' => 'Knitting'],
            ['name' => 'Playing Music'],
            ['name' => 'Skiing'],
            ['name' => 'Surfing'],
            ['name' => 'Yoga'],
            ['name' => 'Writing'],
            ['name' => 'Bird Watching'],
            ['name' => 'Partying'],
            ['name' => 'Shopping'],
            ['name' => 'Singing'],
            ['name' => 'Running'],
            ['name' => 'Bowling'],
            ['name' => 'Camping'],
            ['name' => 'Sewing'],
            ['name' => 'Golfing'],
            ['name' => 'Hunting'],
            ['name' => 'Kayaking'],
            ['name' => 'Sailing'],
            ['name' => 'Scuba Diving'],
            ['name' => 'Snorkeling'],
            ['name' => 'Tennis'],
            ['name' => 'Video Games'],
            ['name' => 'Watching Movies'],
            ['name' => 'Watching TV'],
            ['name' => 'Wine Tasting'],
            ['name' => 'Woodworking'],
            ['name' => 'Writing'],
            ['name' => 'Blogging'],
            ['name' => 'Climbing'],
            ['name' => 'Drawing'],
            ['name' => 'Gaming'],
            ['name' => 'Gymnastics'],
            ['name' => 'Horseback Riding'],
            ['name' => 'Ice Skating'],
            ['name' => 'Meditation'],
            ['name' => 'Origami'],
            ['name' => 'Paintball'],
            ['name' => 'Pottery'],
            ['name' => 'Rafting'],
            ['name' => 'Rock Climbing'],
            ['name' => 'Roller Skating'],
            ['name' => 'Scrapbooking'],
            ['name' => 'Sculpting'],
            ['name' => 'Skateboarding'],
            ['name' => 'Skydiving'],
            ['name' => 'Snowboarding'],
            ['name' => 'Soap Making'],
            ['name' => 'Stand-up Comedy'],
            ['name' => 'Surfing'],
            ['name' => 'Volunteering'],
            ['name' => 'Whale Watching'],
            ['name' => 'Wine Making'],
            ['name' => 'Wood Carving'],
            ['name' => 'Woodworking'],
            ['name' => 'Yoga'],
            ['name' => 'Zumba'],
            ['name' => 'Acting'],
            ['name' => 'Baking'],
            ['name' => 'Blogging'],
            ['name' => 'Board Games'],
            ['name' => 'Book Discussion Clubs'],
            ['name' => 'Book Restoration'],
            ['name' => 'Bowling'],
            ['name' => 'Cabaret'],
            ['name' => 'Calligraphy'],
            ['name' => 'Candle Making'],
            ['name' => 'Candy Making'],
            ['name' => 'Caricatures'],
            ['name' => 'Cheesemaking'],
            ['name' => 'Clothes Making'],
            ['name' => 'Coffee Roasting'],
            ['name' => 'Collecting'],
            ['name' => 'Coloring'],
            ['name' => 'Computer Programming'],
            ['name' => 'Confectionery'],
            ['name' => 'Cooking'],
            ['name' => 'Cosplaying'],
            ['name' => 'Couponing'],
            ['name' => 'Craft'],
            ['name' => 'Creative Writing'],
            ['name' => 'Crocheting'],
            ['name' => 'Cross-Stitch'],
            ['name' => 'Crossword Puzzles'],
            ['name' => 'Cryptography'],
            ['name' => 'Cue Sports'],
            ['name' => 'Dance'],
            ['name' => 'Digital Arts'],
            ['name' => 'Distro Hopping'],
            ['name' => 'DJing'],
            ['name' => 'Do It Yourself'],
            ['name' => 'Drama'],
            ['name' => 'Drawing'],
            ['name' => 'Drink Mixing'],
            ['name' => 'Electronics'],
            ['name' => 'Embroidery'],
            ['name' => 'Experimenting'],
            ['name' => 'Fantasy Sports'],
            ['name' => 'Fashion'],
            ['name' => 'Fashion Design'],
            ['name' => 'Fishkeeping'],
            ['name' => 'Storytelling'],
            ['name' => 'Table Tennis'],
            ['name' => 'Volleyball'],
            ['name' => 'Weightlifting'],
            ['name' => 'Wrestling'],
            ['name' => 'Zumba'],
            ['name' => 'Astronomy'],
            ['name' => 'Beekeeping'],
            ['name' => 'Chess'],
            ['name' => 'Collecting'],
        ]);
    }
}
