<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Worlists extends Seeder
{
    private function getWordListConfigurations()
    {
        return [
            [
                'listName' => 'EgnlishA1 zu Deutsch',
                'description' => 'English A1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 9,
                'wordPairs' => [
                    ["ja", "yes"],
                    ["nein", "no"],
                    ["danke", "thank you"],
                    ["bitte", "please"],
                    ["ich", "I"],
                    ["du", "you"],
                    ["er", "he"],
                    ["sie", "she"],
                    ["es", "it"],
                    ["wir", "we"],
                    ["ihr", "you (plural)"],
                    ["sie (Plural)", "they"],
                    ["gut", "good"],
                    ["schule", "school"],
                    ["essen", "eat"],
                    ["trinken", "drink"],
                    ["buch", "book"],
                    ["haus", "house"],
                    ["auto", "car"],
                    ["zeit", "time"]
                ],
            ],
            [
                'listName' => 'EgnlishA2 zu Deutsch',
                'description' => 'English A2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 10,
                'wordPairs' => [
                    ["Auto", "car"],
                    ["Haus", "house"],
                    ["Apfel", "apple"],
                    ["Tisch", "table"],
                    ["Buch", "book"],
                    ["Blume", "flower"],
                    ["Hund", "dog"],
                    ["Katze", "cat"],
                    ["Mann", "man"],
                    ["Frau", "woman"],
                    ["Kind", "child"],
                    ["Freund", "friend"],
                    ["Essen", "food"],
                    ["Trinken", "drink"],
                    ["Geld", "money"],
                    ["Arbeit", "work"],
                    ["Stadt", "city"],
                    ["Land", "country"],
                    ["Wasser", "water"],
                    ["Himmel", "sky"]
                ],
            ],
            [
                'listName' => 'EgnlishB1 zu Deutsch',
                'description' => 'English B1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 11,
                'wordPairs' => [
                    ["guten Morgen", "good morning"],
                    ["Auto", "car"],
                    ["glücklich", "happy"],
                    ["essen", "eat"],
                    ["Haus", "house"],
                    ["schreiben", "write"],
                    ["Freund", "friend"],
                    ["Musik", "music"],
                    ["trinken", "drink"],
                    ["Arbeit", "work"],
                    ["Tasche", "bag"],
                    ["lachen", "laugh"],
                    ["Buch", "book"],
                    ["reisen", "travel"],
                    ["Familie", "family"],
                    ["lernen", "learn"],
                    ["Stadt", "city"],
                    ["Telefon", "phone"],
                    ["spielen", "play"],
                    ["Essen", "food"]

                ],

            ],
            [
                'listName' => 'EgnlishB2 zu Deutsch',
                'description' => 'English B2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 12,
                'wordPairs' => [
                    ["Auto", "car"],
                    ["Freude", "joy"],
                    ["laufen", "run"],
                    ["Haus", "house"],
                    ["glücklich", "happy"],
                    ["essen", "eat"],
                    ["Stadt", "city"],
                    ["trinken", "drink"],
                    ["Arbeit", "work"],
                    ["lesen", "read"],
                    ["Freund", "friend"],
                    ["lernen", "learn"],
                    ["Musik", "music"],
                    ["reisen", "travel"],
                    ["Wetter", "weather"],
                    ["Kaffee", "coffee"],
                    ["Tasche", "bag"],
                    ["Telefon", "phone"],
                    ["feiern", "celebrate"],
                    ["Buch", "book"]
                    
                ]
            ],
                [
                'listName' => 'EgnlishC1 zu Deutsch',
                'description' => 'English C1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 13,
                'wordPairs'=> [
                    ["glücklich", "happy"],
                    ["freundlich", "friendly"],
                    ["intelligent", "intelligent"],
                    ["verantwortungsbewusst", "responsible"],
                    ["erfolgreich", "successful"],
                    ["interessant", "interesting"],
                    ["entspannt", "relaxed"],
                    ["kreativ", "creative"],
                    ["zufrieden", "satisfied"],
                    ["unabhängig", "independent"],
                    ["aufregend", "exciting"],
                    ["verlässlich", "reliable"],
                    ["geduldig", "patient"],
                    ["leidenschaftlich", "passionate"],
                    ["selbstbewusst", "self-confident"],
                    ["neugierig", "curious"],
                    ["höflich", "polite"],
                    ["energisch", "energetic"],
                    ["optimistisch", "optimistic"],
                    ["flexibel", "flexible"]
                ]
                
            ],
            [
                'listName' => 'EgnlishC2 zu Deutsch',
                'description' => 'English C2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 14,
                'wordPairs'=> [
                    ["sprache", "language"],
                    ["lernen", "learn"],
                    ["fortgeschritten", "advanced"],
                    ["verstehen", "understand"],
                    ["kommunizieren", "communicate"],
                    ["herausforderung", "challenge"],
                    ["gelegenheit", "opportunity"],
                    ["fähigkeit", "ability"],
                    ["fortschritt", "progress"],
                    ["kommunikation", "communication"],
                    ["effizient", "efficient"],
                    ["erfolgreich", "successful"],
                    ["intelligent", "intelligent"],
                    ["komplex", "complex"],
                    ["entwicklung", "development"],
                    ["kreativität", "creativity"],
                    ["unabhängig", "independent"],
                    ["flexibilität", "flexibility"],
                    ["motivation", "motivation"],
                    ["wissen", "knowledge"]
                ]
                
            ],
            [
                'listName' => 'FranzösischA1 zu Deutsch',
                'description' => 'Französisch A1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 16,
                'wordPairs'=> [
                    ["oui", "yes"],
                    ["non", "no"],
                    ["merci", "thank you"],
                    ["s'il vous plaît", "please"],
                    ["je", "I"],
                    ["tu", "you"],
                    ["il", "he"],
                    ["elle", "she"],
                    ["nous", "we"],
                    ["vous", "you (plural)"],
                    ["ils", "they"],
                    ["bon", "good"],
                    ["école", "school"],
                    ["manger", "eat"],
                    ["boire", "drink"],
                    ["livre", "book"],
                    ["maison", "house"],
                    ["voiture", "car"],
                    ["temps", "time"]
                ]
            ],
            [
                'listName' => 'FranzösischA2 zu Deutsch',
                'description' => 'Französisch A2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 17,
                'wordPairs' =>[
                    ["apfel", "pomme"],
                    ["haus", "maison"],
                    ["auto", "voiture"],
                    ["essen", "manger"],
                    ["trinken", "boire"],
                    ["früh", "tôt"],
                    ["spät", "tard"],
                    ["groß", "grand"],
                    ["klein", "petit"],
                    ["gut", "bien"],
                    ["schlecht", "mal"],
                    ["neu", "nouveau"],
                    ["alt", "vieux"],
                    ["heiß", "chaud"],
                    ["kalt", "froid"],
                    ["langsam", " lent"],
                    ["schnell", "rapide"],
                    ["freund", "ami"],
                    ["liebe", "amour"],
                    ["schule", "école"]
                ]
                
            ],
            [
                'listName' => 'FranzösischB1 zu Deutsch',
                'description' => 'Französisch B1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 18,
                'wordPairs' => [
                    ["guten Morgen", "bonjour"],
                    ["guten Tag", "bonjour"],
                    ["guten Abend", "bonsoir"],
                    ["gute Nacht", "bonne nuit"],
                    ["Auto", "voiture"],
                    ["glücklich", "heureux"],
                    ["essen", "manger"],
                    ["Haus", "maison"],
                    ["schreiben", "écrire"],
                    ["Freund", "ami"],
                    ["Musik", "musique"],
                    ["trinken", "boire"],
                    ["Arbeit", "travail"],
                    ["Tasche", "sac"],
                    ["lachen", "rire"],
                    ["Buch", "livre"],
                    ["reisen", "voyager"],
                    ["Familie", "famille"],
                    ["lernen", "apprendre"],
                    ["Stadt", "ville"],
                    ["Telefon", "téléphone"]
                ]
            ],
            [
                'listName' => 'FranzösischB2 zu Deutsch',
                'description' => 'Französisch B2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 19,
                'wordPairs' => [
                    ["Auto", "voiture"],
                    ["Freude", "joie"],
                    ["laufen", "courir"],
                    ["Haus", "maison"],
                    ["glücklich", "heureux"],
                    ["essen", "manger"],
                    ["Stadt", "ville"],
                    ["trinken", "boire"],
                    ["Arbeit", "travail"],
                    ["lesen", "lire"],
                    ["Freund", "ami"],
                    ["lernen", "apprendre"],
                    ["Musik", "musique"],
                    ["reisen", "voyager"],
                    ["Wetter", "météo"],
                    ["Kaffee", "café"],
                    ["Tasche", "sac"],
                    ["Telefon", "téléphone"],
                    ["feiern", "célébrer"],
                    ["Buch", "livre"]
                ]
            ],
            [
                'listName' => 'FranzösischC1 zu Deutsch',
                'description' => 'Französisch C1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 20,
                'wordPairs' => [
                    ["glücklich", "heureux"],
                    ["freundlich", "amical"],
                    ["intelligent", "intelligent"],
                    ["verantwortungsbewusst", "responsable"],
                    ["erfolgreich", "réussi"],
                    ["interessant", "intéressant"],
                    ["entspannt", "détendu"],
                    ["kreativ", "créatif"],
                    ["zufrieden", "satisfait"],
                    ["unabhängig", "indépendant"],
                    ["aufregend", "excitant"],
                    ["verlässlich", "fiable"],
                    ["geduldig", "patient"],
                    ["leidenschaftlich", "passionné"],
                    ["selbstbewusst", "confiant"],
                    ["neugierig", "curieux"],
                    ["höflich", "poli"],
                    ["energisch", "énergique"],
                    ["optimistisch", "optimiste"],
                    ["flexibel", "flexible"]
                ]
            ],
            [
                'listName' => 'FranzösischC2 zu Deutsch',
                'description' => 'Französisch C2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 21,
                'wordPairs' => [
                    ["sprache", "langue"],
                    ["lernen", "apprendre"],
                    ["fortgeschritten", "avancé"],
                    ["verstehen", "comprendre"],
                    ["kommunizieren", "communiquer"],
                    ["herausforderung", "défi"],
                    ["gelegenheit", "occasion"],
                    ["fähigkeit", "capacité"],
                    ["fortschritt", "progrès"],
                    ["kommunikation", "communication"],
                    ["effizient", "efficace"],
                    ["erfolgreich", "réussi"],
                    ["intelligent", "intelligent"],
                    ["komplex", "complexe"],
                    ["entwicklung", "développement"],
                    ["kreativität", "créativité"],
                    ["unabhängig", "indépendant"],
                    ["flexibilität", "flexibilité"],
                    ["motivation", "motivation"],
                    ["wissen", "connaissance"]
                ]
            ],
            [
                'listName' => 'RussischA1 zu Deutsch',
                'description' => 'Russisch A1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 23,
                'wordPairs' => [
                    ["да", "ja"],
                    ["нет", "nein"],
                    ["спасибо", "danke"],
                    ["пожалуйста", "bitte"],
                    ["я", "ich"],
                    ["ты", "du"],
                    ["он", "er"],
                    ["она", "sie"],
                    ["оно", "es"],
                    ["мы", "wir"],
                    ["вы", "ihr"],
                    ["они", "sie"],
                    ["хорошо", "gut"],
                    ["школа", "schule"],
                    ["есть", "essen"],
                    ["пить", "trinken"],
                    ["книга", "buch"],
                    ["дом", "haus"],
                    ["машина", "auto"],
                    ["время", "zeit"],
                    ["morgen", "завтра"],
                    ["Freund", "друг"],
                    ["Haus", "дом"],
                    ["Auto", "машина"],
                    ["klein", "маленький"],
                    ["groß", "большой"],
                    ["schlafen", "спать"],
                ]    
            ],
            [
                'listName' => 'RussischA2 zu Deutsch',
                'description' => 'Russisch A2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 24,
                'wordPairs' => [
                    ["Apfel", "яблоко"],
                    ["Haus", "дом"],
                    ["Auto", "машина"],
                    ["essen", "есть"],
                    ["trinken", "пить"],
                    ["früh", "рано"],
                    ["spät", "поздно"],
                    ["groß", "большой"],
                    ["klein", "маленький"],
                    ["gut", "хорошо"],
                    ["schlecht", "плохо"],
                    ["neu", "новый"],
                    ["alt", "старый"],
                    ["heiß", "горячий"],
                    ["kalt", "холодный"],
                    ["langsam", "медленный"],
                    ["schnell", "быстрый"],
                    ["Freund", "друг"],
                    ["Liebe", "любовь"],
                    ["Schule", "школа"],
                    ["lernen", "учить"],
                    ["lesen", "читать"],
                    ["Musik", "музыка"],
                    ["reisen", "путешествовать"],
                    ["Wetter", "погода"],
                    ["Kaffee", "кофе"],
                    ["Tasche", "сумка"],
                    ["Telefon", "телефон"],
                    ["feiern", "праздновать"],
                    ["Buch", "книга"],
                    ["Familie", "семья"],
                    ["Stadt", "город"],
                    ["Arbeit", "работа"],
                    ["trinken", "пить"],
                    ["essen", "есть"],
                    ["lachen", "смеяться"],
                    ["schreiben", "писать"],
                    ["glücklich", "счастливый"],
                    ["Haus", "дом"],
                    ["Auto", "машина"],
                    ["Freund", "друг"],
                    ["Musik", "музыка"],
                    ["Buch", "книга"],
                    ["lernen", "учить"],
                ]
            ],
            [
                'listName' => 'RussischB1 zu Deutsch',
                'description' => 'Russisch B1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 25,
                'wordPairs' => [
                    ["guten Morgen", "доброе утро"],
                    ["guten Tag", "добрый день"],
                    ["guten Abend", "добрый вечер"],
                    ["gute Nacht", "спокойной ночи"],
                    ["Auto", "машина"],
                    ["glücklich", "счастливый"],
                    ["essen", "есть"],
                    ["Haus", "дом"],
                    ["schreiben", "писать"],
                    ["Freund", "друг"],
                    ["Musik", "музыка"],
                    ["trinken", "пить"],
                    ["Arbeit", "работа"],
                    ["Tasche", "сумка"],
                    ["lachen", "смеяться"],
                    ["Buch", "книга"],
                    ["reisen", "путешествовать"],
                    ["Familie", "семья"],
                    ["lernen", "учить"],
                    ["Stadt", "город"],
                    ["Telefon", "телефон"],
                    ["spielen", "играть"],
                    ["Essen", "еда"],
                    ["trinken", "пить"],
                    ["Auto", "машина"],
                    ["Freude", "радость"],
                    ["laufen", "бегать"],
                    ["Haus", "дом"],
                    ["glücklich", "счастливый"],
                    ["essen", "есть"],
                    ["Stadt", "город"],
                    ["trinken", "пить"],
                    ["Arbeit", "работа"],
                    ["lesen", "читать"],
                    ["Freund", "друг"],
                    ["lernen", "учить"],
                    ["Musik", "музыка"],
                    ["reisen", "путешествовать"],
                    ["Wetter", "погода"],
                    ["Kaffee", "кофе"],
                    ["Tasche", "сумка"],
                    ["Telefon", "телефон"],
                    ["feiern", "праздновать"],
                    ["Buch", "книга"],
                ]
            ],
            [
                'listName' => 'RussischB2 zu Deutsch',
                'description' => 'Russisch B2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 26,
                'wordPairs' => [
                    ["sprechen", "говорить"],
                    ["lernen", "учиться"],
                    ["glücklich", "счастливый"],
                    ["arbeiten", "работать"],
                    ["freundlich", "дружелюбный"],
                    ["essen", "есть"],
                    ["reisen", "путешествовать"],
                    ["schreiben", "писать"],
                    ["interessant", "интересный"],
                    ["trinken", "пить"],
                    ["verstehen", "понимать"],
                    ["schlafen", "спать"],
                    ["schwierig", "трудный"],
                    ["lieben", "любить"],
                    ["lesen", "читать"],
                    ["fröhlich", "веселый"],
                    ["kaufen", "покупать"],
                    ["spielen", "играть"],
                    ["schönheit", "красота"],
                    ["antworten", "отвечать"],
                    ["Wetter", "погода"],
                    ["Kaffee", "кофе"],
                    ["Tasche", "сумка"],
                    ["Telefon", "телефон"],
                    ["feiern", "праздновать"],
                    ["Buch", "книга"],
                    ["Familie", "семья"],
                    ["Stadt", "город"],
                    ["Arbeit", "работа"],
                    ["trinken", "пить"],
                    ["essen", "есть"],
                    ["lachen", "смеяться"],
                    ["schreiben", "писать"],
                    ["glücklich", "счастливый"],
                    ["Haus", "дом"],
                    ["Auto", "машина"],
                    ["Freund", "друг"],
                    ["Musik", "музыка"],
                    ["Buch", "книга"],
                    ["lernen", "учить"],
                    ["Auto", "машина"],
                    ["Freude", "радость"],
                    ["laufen", "бегать"],
                    ["Haus", "дом"],
                    ["glücklich", "счастливый"],
                    ["essen", "есть"],
                    ["Stadt", "город"],
                    ["trinken", "пить"],
                ]
            ],
            [
                'listName' => 'RussischC1 zu Deutsch',
                'description' => 'Russisch C1 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 27,
                'wordPairs' => [
                    ["glücklich", "счастливый"],
                    ["freundlich", "дружелюбный"],
                    ["intelligent", "интеллектуальный"],
                    ["verantwortungsbewusst", "ответственный"],
                    ["erfolgreich", "успешный"],
                    ["interessant", "интересный"],
                    ["entspannt", "расслабленный"],
                    ["kreativ", "креативный"],
                    ["zufrieden", "довольный"],
                    ["unabhängig", "независимый"],
                    ["aufregend", "захватывающий"],
                    ["verlässlich", "надежный"],
                    ["geduldig", "терпеливый"],
                    ["leidenschaftlich", "страстный"],
                    ["selbstbewusst", "уверенный в себе"],
                    ["neugierig", "любопытный"],
                    ["höflich", "вежливый"],
                    ["energisch", "энергичный"],
                    ["optimistisch", "оптимистичный"],
                    ["flexibel", "гибкий"],
                    ["fröhlich", "веселый"],
                    ["kaufen", "покупать"],
                    ["spielen", "играть"],
                    ["schönheit", "красота"],
                    ["antworten", "отвечать"]
                ]
            ],
            [
                'listName' => 'RussischC2 zu Deutsch',
                'description' => 'Russisch C2 WörterListe mit deutsch als Basissprache',
                'baseLanguageId' => 1,
                'targetLanguageId' => 28,
                'wordPairs' =>[
                    ["lernen", "учиться"],
                    ["fortgeschritten", "продвинутый"],
                    ["verstehen", "понимать"],
                    ["kommunizieren", "общаться"],
                    ["herausforderung", "вызов"],
                    ["gelegenheit", "возможность"],
                    ["fähigkeit", "способность"],
                    ["fortschritt", "прогресс"],
                    ["kommunikation", "коммуникация"],
                    ["effizient", "эффективный"],
                    ["erfolgreich", "успешный"],
                    ["intelligent", "интеллектуальный"],
                    ["komplex", "сложный"],
                    ["entwicklung", "развитие"],
                    ["kreativität", "креативность"],
                    ["unabhängig", "независимый"],
                    ["flexibilität", "гибкость"],
                    ["motivation", "мотивация"],
                    ["wissen", "знание"],
                    ["sprechen", "говорить"],
                    ["lernen", "учиться"],
                    ["glücklich", "счастливый"],
                    ["arbeiten", "работать"],
                    ["freundlich", "дружелюбный"],
                    ["essen", "есть"],
                    ["reisen", "путешествовать"],
                    ["schreiben", "писать"],
                    ["interessant", "интересный"],
                    ["verstehen", "понимать"],
                    ["schlafen", "спать"],
                    ["schwierig", "трудный"],
                    ["lieben", "любить"],
                    ["lesen", "читать"],
                    ["fröhlich", "веселый"],
                    ["kaufen", "покупать"],
                    ["spielen", "играть"],
                    ["schönheit", "красота"],
                    ["antworten", "отвечать"]
                ]
            ],
            [
                'listName' =>'PortugiesischA1 zu Deutsch',
                'description' => 'Portugiesisch A1(brasilianisch) WörterListe mit deutsch als Basissprache ',
                'baseLanguageId' => 1,
                'targetLanguageId' => 30,
                'wordPairs' =>[
                    ["ja", "sim"],
                    ["nein", "não"],
                    ["gut", "bom"],
                    ["schlecht", "ruim"],
                    ["danke", "obrigado"],
                    ["bitte", "por favor"],
                    ["ich", "eu"],
                    ["du", "você"],
                    ["essen", "comer"],
                    ["trinken", "beber"],
                    ["gehen", "ir"],
                    ["kommen", "vir"],
                    ["groß", "grande"],
                    ["klein", "pequeno"],
                    ["früh", "cedo"],
                    ["spät", "tarde"],
                    ["Haus", "casa"],
                    ["Auto", "carro"],
                    ["Freund", "amigo"],
                    ["Familie", "família"]
                ]
            ],
            [
                'listName' => 'PortugiesischA2 zu Deutsch',
                'description' => 'Portugiesisch A2(brasilianisch) WörterListe mit deutsch als Basissprache ',
                'baseLanguageId' => 1,
                'targetLanguageId' => 31,
                'wordPairs' => [
                    ["Auto", "carro"],
                    ["Haus", "casa"],
                    ["essen", "comer"],
                    ["trinken", "beber"],
                    ["glücklich", "feliz"],
                    ["traurig", "triste"],
                    ["groß", "grande"],
                    ["klein", "pequeno"],
                    ["sprechen", "falar"],
                    ["hören", "ouvir"],
                    ["schlafen", "dormir"],
                    ["wecken", "acordar"],
                    ["lernen", "aprender"],
                    ["buchen", "reservar"],
                    ["öffnen", "abrir"],
                    ["schließen", "fechar"],
                    ["gehen", "ir"],
                    ["kommen", "vir"],
                    ["arbeiten", "trabalhar"],
                    ["spielen", "jogar"]

                ]
            ],
            [
                'listName' => 'PortugiesischB1 zu Deutsch',
                'description' => 'Portugiesisch B1(brasilianisch) WörterListe mit deutsch als Basissprache ',
                'baseLanguageId' => 1,
                'targetLanguageId' => 32,
                'wordPairs' =>[
                    ["glücklich", "feliz"],
                    ["traurig", "triste"],
                    ["groß", "grande"],
                    ["klein", "pequeno"],
                    ["arbeiten", "trabalhar"],
                    ["studieren", "estudar"],
                    ["früh", "cedo"],
                    ["spät", "tarde"],
                    ["freundlich", "amigável"],
                    ["wichtig", "importante"],
                    ["schlafen", "dormir"],
                    ["lachen", "rir"],
                    ["Buch", "livro"],
                    ["Telefon", "telefone"],
                    ["Blume", "flor"],
                    ["Geld", "dinheiro"],
                    ["kommen", "vir"],
                    ["spielen", "jogar"],
                    ["lernen", "aprender"],
                    ["öffnen", "abrir"],
                    ["schließen", "fechar"],
                    ["sprechen", "falar"],
                    ["hören", "ouvir"],
                    ["wecken", "acordar"],
                    ["buchen", "reservar"]
                ]
            ],
            [
                'listName' => 'PortugiesischB2 zu Deutsch',
                'description' => 'Portugiesisch B2(brasilianisch) WörterListe mit deutsch als Basissprache ',
                'baseLanguageId' => 1,
                'targetLanguageId' => 33,
                'wordPairs' => [
                    ["apfel", "maçã"],
                    ["blau", "azul"],
                    ["tanzen", "dançar"],
                    ["kochen", "cozinhar"],
                    ["freundlich", "amigável"],
                    ["lesen", "ler"],
                    ["frühstück", "café da manhã"],
                    ["gitarre", "violão"],
                    ["glücklich", "feliz"],
                    ["schreiben", "escrever"],
                    ["auto", "carro"],
                    ["berge", "montanhas"],
                    ["lernen", "aprender"],
                    ["film", "filme"],
                    ["reisen", "viajar"],
                    ["regen", "chuva"],
                    ["schwimmen", "nadar"],
                    ["natur", "natureza"],
                    ["singen", "cantar"],
                    ["träumen", "sonhar"],
                    ["laufen", "correr"],
                    ["Haus", "casa"],
                    ["glücklich", "feliz"],
                    ["essen", "comer"],
                    ["Stadt", "cidade"],
                    ["trinken", "beber"],
                    ["arbeiten", "trabalhar"],
                    ["lesen", "ler"],
                    ["Freund", "amigo"],
                    ["lernen", "aprender"],
                    ["Musik", "música"],
                    ["reisen", "viajar"],
                    ["Wetter", "tempo"],
                    ["Kaffee", "café"],
                    ["Tasche", "saco"],
                    ["Telefon", "telefone"],
                    ["feiern", "comemorar"],
                    ["Buch", "livro"],
                    ["Familie", "família"],
                    ["Stadt", "cidade"],
                    ["Arbeit", "trabalho"],
                ]
            ],
            [
                'listName' => 'PortugiesischC1 zu Deutsch',
                'description' => 'Portugiesisch C1(brasilianisch) WörterListe mit deutsch als Basissprache ',
                'baseLanguageId' => 1,
                'targetLanguageId' => 34,
                'wordPairs' =>[
                    ["glücklich", "feliz"],
                    ["freundlich", "amigável"],
                    ["intelligent", "inteligente"],
                    ["verantwortungsbewusst", "responsável"],
                    ["erfolgreich", "bem sucedido"],
                    ["interessant", "interessante"],
                    ["entspannt", "relaxado"],
                    ["kreativ", "criativo"],
                    ["zufrieden", "satisfeito"],
                    ["unabhängig", "independente"],
                    ["aufregend", "emocionante"],
                    ["verlässlich", "confiável"],
                    ["geduldig", "paciente"],
                    ["leidenschaftlich", "apaixonado"],
                    ["selbstbewusst", "autoconfiante"],
                    ["neugierig", "curioso"],
                    ["höflich", "educado"],
                    ["energisch", "energético"],
                    ["optimistisch", "otimista"],
                    ["flexibel", "flexível"],
                    ["fröhlich", "alegre"],
                    ["kaufen", "comprar"],
                    ["spielen", "jogar"],
                    ["schönheit", "beleza"],
                    ["antworten", "responder"],
                    ["sprechen", "falar"],
                    ["lernen", "aprender"],
                    ["glücklich", "feliz"],
                    ["arbeiten", "trabalhar"],
                    ["freundlich", "amigável"],
                    ["essen", "comer"],
                    ["reisen", "viajar"],
                    ["schreiben", "escrever"],
                    ["interessant", "interessante"],
                    ["verstehen", "entender"],
                    ["schlafen", "dormir"],
                    ["schwierig", "difícil"],
                    ["lieben", "amar"],
                    ["lesen", "ler"],
                    ["fröhlich", "alegre"],
                    ["kaufen", "comprar"],
                    ["spielen", "jogar"],
                    ["schönheit", "beleza"],
                    ["antworten", "responder"],
                    ["sprechen", "falar"],
                    ["lernen", "aprender"],
                    ["glücklich", "feliz"],
                    ["arbeiten", "trabalhar"],
                ]
            ],
            [
                'listName' => 'PortugiesischC2 zu Deutsch',
                'description' => 'Portugiesisch C2(brasilianisch) WörterListe mit deutsch als Basissprache ',
                'baseLanguageId' => 1,
                'targetLanguageId' => 35,
                'wordPairs' =>[
                    ["lernen", "aprender"],
                    ["fortgeschritten", "avançado"],
                    ["verstehen", "entender"],
                    ["kommunizieren", "comunicar"],
                    ["herausforderung", "desafio"],
                    ["gelegenheit", "oportunidade"],
                    ["fähigkeit", "habilidade"],
                    ["fortschritt", "progresso"],
                    ["kommunikation", "comunicação"],
                    ["effizient", "eficiente"],
                    ["erfolgreich", "bem sucedido"],
                    ["intelligent", "inteligente"],
                    ["komplex", "complexo"],
                    ["entwicklung", "desenvolvimento"],
                    ["kreativität", "criatividade"],
                    ["unabhängig", "independente"],
                    ["flexibilität", "flexibilidade"],
                    ["motivation", "motivação"],
                    ["wissen", "conhecimento"],
                    ["sprechen", "falar"],
                    ["lernen", "aprender"],
                    ["glücklich", "feliz"],
                    ["arbeiten", "trabalhar"],
                    ["freundlich", "amigável"],
                    ["essen", "comer"],
                    ["reisen", "viajar"],
                    ["schreiben", "escrever"],
                    ["interessant", "interessante"],
                    ["verstehen", "entender"],
                    ["schlafen", "dormir"],
                    ["schwierig", "difícil"],
                    ["lieben", "amar"],
                    ["lesen", "ler"],
                    ["fröhlich", "alegre"],
                    ["kaufen", "comprar"],
                    ["spielen", "jogar"],
                    ["schönheit", "beleza"],
                    ["antworten", "responder"]
                ]
            ]
                    
        ];
    }


    private function insertDataFromConfigurations($configurations)
    {
        foreach ($configurations as $config) {
            $wordListId = DB::table('word_lists')->insertGetId([
                'created_by' => 1, // Admin User ID
                'name' => $config['listName'],
                'description' => $config['description'],
                'base_language' => $config['baseLanguageId'],
                'target_language' => $config['targetLanguageId'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            foreach ($config['wordPairs'] as $pair) {
                $wordId = DB::table('words')->insertGetId([
                    'base_language_id' => $config['baseLanguageId'],
                    'target_language_id' => $config['targetLanguageId'],
                    'base_word' => $pair[0],
                    'target_word' => $pair[1],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                DB::table('word_list_words')->insert([
                    'word_list_id' => $wordListId,
                    'word_id' => $wordId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                DB::table('user_words')->insert([
                    'user_id' => 1, // Admin User ID
                    'word_id' => $wordId,
                    'count' => 0,
                ]);
            }
        }
    }
    public function run(): void
    {
        $configurations = $this->getWordListConfigurations();
        $this->insertDataFromConfigurations($configurations);
    }
}
